// Generated by CoffeeScript 1.6.2
var Engine, Entity, Input, Moving, PlayerControlled, Positioned, Renderable, Renderer, Resources, System, attachMover, attachPlayerController, average, keyForComponent, sum, testEngine,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

sum = function(list) {
  return _.foldl(list, (function(s, x) {
    return s + x;
  }), 0);
};

average = function(list) {
  return sum(list) / list.length;
};

Resources = (function() {
  var callbacks, get, load, onReady, ready, resources;

  resources = {};
  callbacks = [];
  ready = function() {
    return _.all(_.values(resources));
  };
  load = function(url) {
    var img;

    if (resources[url]) {
      return resources[url];
    } else {
      img = new Image();
      img.onload = function() {
        var cb, _i, _len, _results;

        resources[url] = img;
        if (ready()) {
          _results = [];
          for (_i = 0, _len = callbacks.length; _i < _len; _i++) {
            cb = callbacks[_i];
            _results.push(cb());
          }
          return _results;
        }
      };
      resources[url] = false;
      return img.src = url;
    }
  };
  get = function(url) {
    return resources[url];
  };
  onReady = function(callback) {
    callbacks.push(callback);
    if (ready() && !_.isEmpty(resources)) {
      return callback();
    }
  };
  return {
    load: load,
    get: get,
    onReady: onReady
  };
})();

Input = (function() {
  var keys, setKey;

  keys = {};
  setKey = function(event, status) {
    var code, key;

    code = event.keyCode;
    key = (function() {
      switch (code) {
        case 32:
          return "SPACE";
        case 37:
          return "LEFT";
        case 38:
          return "UP";
        case 39:
          return "RIGHT";
        case 40:
          return "DOWN";
        case 187:
          return "+";
        case 189:
          return "-";
        default:
          return String.fromCharCode(code);
      }
    })();
    return keys[key] = status;
  };
  document.addEventListener('keydown', function(e) {
    return setKey(e, true);
  });
  document.addEventListener('keyup', function(e) {
    return setKey(e, false);
  });
  document.addEventListener('blur', function() {
    return keys = {};
  });
  return {
    isDown: function(key) {
      return keys[key.toUpperCase()];
    }
  };
})();

keyForComponent = function(component) {
  return component.constructor.name.toLowerCase();
};

Engine = (function() {
  function Engine() {
    this.gameLoop = __bind(this.gameLoop, this);    this.entities = {};
    this.systems = [];
    this.lastEntityId = 0;
    this.running = false;
    this.lastFrameTime = null;
  }

  Engine.prototype.createEntity = function(components) {
    var c, componentsObject, id, system, _i, _j, _len, _len1, _ref;

    componentsObject = {};
    for (_i = 0, _len = components.length; _i < _len; _i++) {
      c = components[_i];
      componentsObject[keyForComponent(c)] = c;
    }
    id = this.lastEntityId;
    this.entities[id] = componentsObject;
    _ref = this.systems;
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      system = _ref[_j];
      system.updateCache(id, componentsObject);
    }
    this.lastEntityId += 1;
    return new Entity(id, componentsObject, this);
  };

  Engine.prototype.updateEntity = function(id) {
    var components, system, _i, _len, _ref, _results;

    components = this.entities[id];
    _ref = this.systems;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      system = _ref[_i];
      _results.push(system.updateCache(id, components));
    }
    return _results;
  };

  Engine.prototype.addSystem = function(system) {
    this.systems.push(system);
    return system.buildCache(this.entities);
  };

  Engine.prototype.tick = function(dt) {
    var system, _i, _len, _ref, _results;

    _ref = this.systems;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      system = _ref[_i];
      _results.push(system.run(this.entities, dt));
    }
    return _results;
  };

  Engine.prototype.removeDeadEntities = function() {
    var components, id, system, _ref, _results;

    _ref = this.entities;
    _results = [];
    for (id in _ref) {
      components = _ref[id];
      if (components.destroy != null) {
        delete this.entities[id];
        _results.push((function() {
          var _i, _len, _ref1, _results1;

          _ref1 = this.systems;
          _results1 = [];
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            system = _ref1[_i];
            _results1.push(system.updateCache(id, null));
          }
          return _results1;
        }).call(this));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  Engine.prototype.start = function() {
    this.running = true;
    this.lastFrameTime = null;
    return requestAnimationFrame(this.gameLoop);
  };

  Engine.prototype.gameLoop = function(paintTime) {
    var dt;

    if (this.lastFrameTime === null) {
      this.lastFrameTime = paintTime;
      return requestAnimationFrame(this.gameLoop);
    } else {
      dt = (paintTime - this.lastFrameTime) / 1000.0;
      this.lastFrameTime = paintTime;
      if (typeof this.beforeTick === "function") {
        this.beforeTick(dt);
      }
      this.tick(dt);
      this.removeDeadEntities();
      if (typeof this.afterTick === "function") {
        this.afterTick(dt);
      }
      if (this.running) {
        return requestAnimationFrame(this.gameLoop);
      }
    }
  };

  return Engine;

})();

Entity = (function() {
  function Entity(id, components, engine) {
    this.id = id;
    this.components = components;
    this.engine = engine;
  }

  Entity.prototype.addComponent = function(component) {
    var componentObject;

    componentObject = {};
    componentObject[keyForComponent(component)] = component;
    _.extend(this.components, componentObject);
    return this.engine.updateEntity(this.id);
  };

  Entity.prototype.removeComponent = function(componentName) {
    if (_.has(this.components, componentName)) {
      delete this.components[componentName];
      return this.engine.updateEntity(this.id);
    }
  };

  Entity.prototype.destroy = function() {
    return this.components.destroy = true;
  };

  return Entity;

})();

Positioned = (function() {
  function Positioned(pos) {
    this.pos = pos != null ? pos : [0, 0];
  }

  return Positioned;

})();

Renderable = (function() {
  function Renderable(url, pos, size) {
    this.url = url != null ? url : "resources/sun.gif";
    this.pos = pos != null ? pos : [0, 0];
    this.size = size != null ? size : [128, 128];
  }

  return Renderable;

})();

System = (function() {
  function System(satisfies, fn) {
    this.satisfies = satisfies;
    this.fn = fn;
    this.cache = {};
  }

  System.prototype.buildCache = function(entities) {
    var components, id, _results;

    _results = [];
    for (id in entities) {
      components = entities[id];
      if (this.satisfies(components)) {
        _results.push(this.cache[id] = true);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  System.prototype.updateCache = function(id, components) {
    if (components === null || !this.satisfies(components)) {
      if (_.has(this.cache, id)) {
        return delete this.cache[id];
      }
    } else {
      return this.cache[id] = true;
    }
  };

  System.prototype.run = function(entities, dt) {
    var id, _i, _len, _ref, _results;

    _ref = _.keys(this.cache);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      id = _ref[_i];
      if (_.has(entities, id)) {
        _results.push(this.fn(entities[id], dt));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  return System;

})();

Renderer = (function() {
  function Renderer(canvas) {
    var _this = this;

    this.canvas = canvas;
    this.ctx = canvas.getContext('2d');
    this.system = new System(function(components) {
      return _.has(components, "renderable") && _.has(components, "positioned");
    }, function(components, dt) {
      var positioned, renderable;

      renderable = components.renderable;
      positioned = components.positioned;
      return _this.ctx.drawImage(Resources.get(renderable.url), renderable.pos[0], renderable.pos[1], renderable.size[0], renderable.size[1], positioned.pos[0], positioned.pos[1], renderable.size[0], renderable.size[1]);
    });
    this.clearCanvas = function(dt) {
      _this.ctx.fillStyle = "lightgrey";
      return _this.ctx.fillRect(0, 0, _this.canvas.width, _this.canvas.height);
    };
    this.drawFramerate = function(dt) {
      if (_this.showFramerate) {
        return _this.updateAndDrawFramerate(dt);
      }
    };
    this.framerates = [];
    this.showFramerate = true;
  }

  Renderer.prototype.toggleFramerate = function() {
    return this.showFramerate = !this.showFramerate;
  };

  Renderer.prototype.updateAndDrawFramerate = function(dt) {
    var drawFramerate,
      _this = this;

    drawFramerate = function() {
      _this.ctx.save();
      _this.ctx.fillStyle = "black";
      _this.ctx.font = "30px sans-serif";
      _this.ctx.fillText(average(_this.framerates).toFixed(1), 50, 50);
      return _this.ctx.restore();
    };
    this.framerates.push(1 / dt);
    while (this.framerates.length > 10) {
      this.framerates.shift();
    }
    return drawFramerate();
  };

  return Renderer;

})();

Moving = (function() {
  function Moving(velocity) {
    this.velocity = velocity != null ? velocity : [10, 10];
  }

  return Moving;

})();

attachMover = function(engine) {
  var mover;

  mover = new System(function(components) {
    return _.has(components, "positioned") && _.has(components, "moving");
  }, function(components, dt) {
    components.positioned.pos[0] += components.moving.velocity[0] * dt;
    return components.positioned.pos[1] += components.moving.velocity[1] * dt;
  });
  return engine.addSystem(mover);
};

PlayerControlled = (function() {
  function PlayerControlled(playerSpeed) {
    this.playerSpeed = playerSpeed != null ? playerSpeed : 100;
  }

  return PlayerControlled;

})();

attachPlayerController = function(engine) {
  var playerController;

  playerController = new System(function(components) {
    return _.has(components, "playercontrolled") && _.has(components, "positioned");
  }, function(components, dt) {
    var playerSpeed;

    playerSpeed = components.playercontrolled.playerSpeed;
    if (Input.isDown('LEFT')) {
      components.positioned.pos[0] += -playerSpeed * dt;
    }
    if (Input.isDown('RIGHT')) {
      components.positioned.pos[0] += playerSpeed * dt;
    }
    if (Input.isDown('UP')) {
      components.positioned.pos[1] += -playerSpeed * dt;
    }
    if (Input.isDown('DOWN')) {
      return components.positioned.pos[1] += playerSpeed * dt;
    }
  });
  return engine.addSystem(playerController);
};

testEngine = function(engine) {
  var e1, e2, e3;

  e1 = engine.createEntity([new Renderable(), new Positioned()]);
  e2 = engine.createEntity([new Renderable(), new Positioned([200, 200]), new Moving()]);
  e3 = engine.createEntity([new Renderable(), new PlayerControlled()]);
  engine.start();
  _.delay((function() {
    return e1.addComponent(new Moving());
  }), 2000);
  _.delay((function() {
    _.extend(e3.components, {
      "positioned": new Positioned()
    });
    return engine.updateEntity(e3.id);
  }), 4000);
  _.delay((function() {
    return e1.removeComponent("moving");
  }), 10000);
  return _.delay((function() {
    return e2.destroy();
  }), 6000);
};

/*
//@ sourceMappingURL=main.map
*/
